// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpt3QHHtgXprKdqEFRki8hacKBITSl86s',
    appId: '1:617408675528:web:4a1ec02df09cca2e6feffd',
    messagingSenderId: '617408675528',
    projectId: 'speakup-b938b',
    authDomain: 'speakup-b938b.firebaseapp.com',
    storageBucket: 'speakup-b938b.appspot.com',
    measurementId: 'G-N91J3QE9EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Ul7HslpTjfd8BmbWfeNWClCAMWkOEtw',
    appId: '1:617408675528:android:c23efb6806a29d936feffd',
    messagingSenderId: '617408675528',
    projectId: 'speakup-b938b',
    storageBucket: 'speakup-b938b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlw7GUf0USJ222nkuJ7HikeNCKQy6N9_U',
    appId: '1:617408675528:ios:8e66a69222a5ecb06feffd',
    messagingSenderId: '617408675528',
    projectId: 'speakup-b938b',
    storageBucket: 'speakup-b938b.appspot.com',
    iosBundleId: 'com.example.speakup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlw7GUf0USJ222nkuJ7HikeNCKQy6N9_U',
    appId: '1:617408675528:ios:c3be5bcc44643ace6feffd',
    messagingSenderId: '617408675528',
    projectId: 'speakup-b938b',
    storageBucket: 'speakup-b938b.appspot.com',
    iosBundleId: 'com.example.speakup.RunnerTests',
  );
}
